### ISSUE TITLE
[feat] add more subscription snippets

### ISSUE THREAD

**Issue by TomerFi** [ilan-pinto/ocm-vscode-extension#16]
The current subscription snippet is of a git-typed application, adding two more snippets for helm-typed and object-typed applications, should be a good idea and quite easy to accomplish.

**Comment by TomerFi** [comment]
To be more specific, in a similar manner to the [subscription-git snippet](https://github.com/ilan-pinto/ocm-vscode-extension/blob/main/snippets/subscription_git.json),
we need to add snippets for other application types besides git,
such as _helmrepo_, _objectbucket_, and _namespace_.

**Comment by vbelouso** [comment]
@ilan-pinto please assign this issue to me
